import type OpenAI from 'openai'

// Shared by /api/v1/scan (manual/re-check) and the post-humanize auto-check
// in /api/v1/humanize, so both use identical detection logic instead of two
// copies drifting apart.

// ── Rule-based pre-filter (O(n), no ML needed) ──────────────────────────────

const BOT_SIGNATURES = [
  'as an ai language model',
  'as a large language model',
  'as an artificial intelligence',
  "i'm an ai and",
  'i am an ai assistant',
  'i cannot assist with that',
  "i'm not able to help with",
  'i must clarify that as an ai',
]

const BOT_PATTERNS = [
  /as an ai(?:\s+language)?\s+model/i,
  /i(?:'m| am) programmed to/i,
  /my (?:training data|knowledge cutoff)/i,
  /i don'?t have (?:personal )?(?:opinions|feelings|consciousness)/i,
]

const HUMAN_SIGNALS = [
  /\bi (?:think|feel|believe|reckon|suppose|guess)\b/i,
  /\bto be (?:honest|fair|blunt)\b/i,
  /\bhonestly\b/i,
  /\byou know what\b/i,
  /\bdon't get me wrong\b/i,
]

export function ruleFilter(text: string): 'ai-generated' | 'human-written' | 'uncertain' | null {
  const lower = text.toLowerCase()
  for (const sig of BOT_SIGNATURES) {
    if (lower.includes(sig)) return 'ai-generated'
  }
  for (const pat of BOT_PATTERNS) {
    if (pat.test(text)) return 'ai-generated'
  }

  const words = text.split(/\s+/)
  const uniqueWords = new Set(words.map(w => w.toLowerCase())).size
  if (words.length < 50 && uniqueWords < 20) return 'uncertain'

  const humanHits = HUMAN_SIGNALS.filter(p => p.test(text)).length
  if (humanHits >= 3) return 'human-written'

  return null
}

// ── Model-based classifier ───────────────────────────────────────────────────

export interface FeatureContribution {
  feature: string
  observed_value: number
  direction: 'ai_indicator' | 'human_indicator'
  contribution: number
}

export interface ClassifyResult {
  classification: 'human-written' | 'ai-generated' | 'mixed' | 'uncertain'
  confidence: number
  human_probability: number
  ai_probability: number
  uncertain_probability: number
  top_features: FeatureContribution[]
  explanation: { summary: string; detail: string }
  model_used: string
}

const QUICK_MODE_ANALYSIS_CHARS = 4_000
const STANDARD_MODE_ANALYSIS_CHARS = 40_000

async function classifyWithModel(
  client: OpenAI,
  model: string,
  text: string,
  mode: 'quick' | 'standard',
): Promise<ClassifyResult> {
  const prompt = `Analyze whether the following text was written by a human or generated by AI.

Return ONLY a JSON object with this exact shape:
{
  "classification": "human-written" | "ai-generated" | "mixed" | "uncertain",
  "confidence": <0.0–1.0>,
  "human_probability": <0.0–1.0>,
  "ai_probability": <0.0–1.0>,
  "top_signals": [
    { "feature": "<signal name>", "direction": "ai_indicator" | "human_indicator", "contribution": <0.0–1.0> }
  ],
  "explanation_summary": "<one sentence>",
  "explanation_detail": "<2–3 sentences with specific evidence>"
}

Signals to check: transition word density, sentence length variance, vocabulary diversity,
passive voice ratio, hedging language, first-person markers, informal contractions,
rhetorical questions, em-dash usage, paragraph opener variety.

TEXT:
${text.slice(0, mode === 'quick' ? QUICK_MODE_ANALYSIS_CHARS : STANDARD_MODE_ANALYSIS_CHARS)}`

  const completion = await client.chat.completions.create({
    model,
    messages: [{ role: 'user', content: prompt }],
    response_format: { type: 'json_object' },
    temperature: 0,
  })

  const raw = JSON.parse(completion.choices[0]?.message?.content ?? '{}')
  const classification = (['human-written', 'ai-generated', 'mixed', 'uncertain'].includes(raw.classification)
    ? raw.classification
    : 'uncertain') as ClassifyResult['classification']

  const confidence = Math.min(1, Math.max(0, Number(raw.confidence) || 0.5))
  const humanProb = Math.min(1, Math.max(0, Number(raw.human_probability) || 0.5))
  const aiProb = Math.min(1, Math.max(0, Number(raw.ai_probability) || 0.5))
  const uncertainProb = classification === 'uncertain' ? 1 - confidence : 0

  const topFeatures = (Array.isArray(raw.top_signals) ? raw.top_signals : [])
    .slice(0, 5)
    .map((s: { feature?: string; direction?: string; contribution?: number }, i: number) => ({
      feature: String(s.feature ?? `signal_${i}`),
      observed_value: Number(s.contribution ?? 0),
      direction: s.direction === 'human_indicator' ? 'human_indicator' : ('ai_indicator' as const),
      contribution: Math.min(1, Math.max(0, Number(s.contribution ?? 0))),
    }))

  return {
    classification,
    confidence,
    human_probability: humanProb,
    ai_probability: aiProb,
    uncertain_probability: uncertainProb,
    top_features: topFeatures,
    explanation: {
      summary: String(raw.explanation_summary ?? `Text classified as ${classification} with ${Math.round(confidence * 100)}% confidence.`),
      detail: String(raw.explanation_detail ?? ''),
    },
    model_used: completion.model,
  }
}

const CANNED_RESULTS: Record<'ai-generated' | 'human-written' | 'uncertain', ClassifyResult> = {
  'ai-generated': {
    classification: 'ai-generated',
    confidence: 0.99,
    human_probability: 0.01,
    ai_probability: 0.99,
    uncertain_probability: 0,
    top_features: [{ feature: 'bot_signature', observed_value: 1, direction: 'ai_indicator', contribution: 1 }],
    explanation: {
      summary: 'Text classified as ai-generated with 99% confidence.',
      detail: 'AI bot signature phrase detected (rule-based filter).',
    },
    model_used: 'rule_filter',
  },
  'human-written': {
    classification: 'human-written',
    confidence: 0.85,
    human_probability: 0.85,
    ai_probability: 0.15,
    uncertain_probability: 0,
    top_features: [{ feature: 'informal_human_signals', observed_value: 1, direction: 'human_indicator', contribution: 0.85 }],
    explanation: {
      summary: 'Text classified as human-written with 85% confidence.',
      detail: 'Multiple informal human-writing signals detected (hedging, first-person markers).',
    },
    model_used: 'rule_filter',
  },
  uncertain: {
    classification: 'uncertain',
    confidence: 0.5,
    human_probability: 0.5,
    ai_probability: 0.5,
    uncertain_probability: 0.5,
    top_features: [],
    explanation: {
      summary: 'Classification is uncertain.',
      detail: 'Text is too short or has too few unique words for reliable classification.',
    },
    model_used: 'rule_filter',
  },
}

// Runs the fast rule-based prefilter first, falls back to the model classifier.
export async function classify(
  client: OpenAI,
  model: string,
  text: string,
  mode: 'quick' | 'standard' = 'standard',
): Promise<ClassifyResult> {
  const ruleResult = ruleFilter(text)
  if (ruleResult) return CANNED_RESULTS[ruleResult]
  return classifyWithModel(client, model, text, mode)
}
