import { describe, it, expect } from 'vitest'
import { DEFAULT_WEIGHTS, computeScore, fitWeights, type WeightFittingSample } from '../weights'
import type { CandidateScores } from '../types'

describe('DEFAULT_WEIGHTS', () => {
  it('weights every dimension equally, summing to 1', () => {
    const values = Object.values(DEFAULT_WEIGHTS)
    expect(values.every(v => v === 0.2)).toBe(true)
    expect(values.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 6)
  })
})

describe('computeScore', () => {
  it('computes the weighted sum across all five dimensions', () => {
    const scores: CandidateScores = { naturalness: 0.5, tone_alignment: 0.6, domain_alignment: 0.7, intensity_alignment: 0.8, coherence: 0.9 }
    // With equal 0.2 weights, this is just the mean of the five scores.
    expect(computeScore(scores)).toBeCloseTo((0.5 + 0.6 + 0.7 + 0.8 + 0.9) / 5, 6)
  })

  it('respects custom weights over the default', () => {
    const scores: CandidateScores = { naturalness: 1, tone_alignment: 0, domain_alignment: 0, intensity_alignment: 0, coherence: 0 }
    expect(computeScore(scores, { naturalness: 1, tone: 0, domain: 0, intensity: 0, coherence: 0 })).toBe(1)
    expect(computeScore(scores, { naturalness: 0, tone: 1, domain: 0, intensity: 0, coherence: 0 })).toBe(0)
  })
})

describe('fitWeights', () => {
  it('falls back to the neutral default with fewer samples than dimensions', () => {
    const samples: WeightFittingSample[] = [
      { scores: { naturalness: 0.5, tone_alignment: 0.5, domain_alignment: 0.5, intensity_alignment: 0.5, coherence: 0.5 }, target: 0.5 },
    ]
    expect(fitWeights(samples)).toEqual(DEFAULT_WEIGHTS)
  })

  it('recovers approximately the true coefficients from noise-free samples generated by a known linear model', () => {
    const trueWeights = { naturalness: 2, tone: 0.5, domain: 1, intensity: 0, coherence: 1.5 }
    const rand = (seed: number) => {
      // Deterministic pseudo-random in [0, 1) — no external dependency, and
      // repeatable across runs.
      const x = Math.sin(seed * 12.9898) * 43758.5453
      return x - Math.floor(x)
    }
    const samples: WeightFittingSample[] = Array.from({ length: 30 }, (_, i) => {
      const scores: CandidateScores = {
        naturalness: rand(i * 4 + 1),
        tone_alignment: rand(i * 4 + 2),
        domain_alignment: rand(i * 4 + 3),
        intensity_alignment: rand(i * 4 + 4),
        coherence: rand(i * 4 + 5),
      }
      const target =
        trueWeights.naturalness * scores.naturalness +
        trueWeights.tone * scores.tone_alignment +
        trueWeights.domain * scores.domain_alignment +
        trueWeights.intensity * scores.intensity_alignment +
        trueWeights.coherence * scores.coherence
      return { scores, target }
    })

    const fitted = fitWeights(samples)
    expect(fitted.naturalness).toBeCloseTo(trueWeights.naturalness, 3)
    expect(fitted.tone).toBeCloseTo(trueWeights.tone, 3)
    expect(fitted.domain).toBeCloseTo(trueWeights.domain, 3)
    expect(fitted.intensity).toBeCloseTo(trueWeights.intensity, 3)
    expect(fitted.coherence).toBeCloseTo(trueWeights.coherence, 3)
  })
})
